name: Python Tests

on: 
  push: 
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repo
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python_api/requirements.txt
      
      # Step 4: Set up Java (Required for Allure CLI)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use the OpenJDK distribution
          java-version: '11'
      
      # Step 5: Install Allure CLI
      - name: Install Allure CLI
        run: |
          curl -o allure-commandline.zip -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.20.1/allure-commandline-2.20.1.zip
          unzip -o allure-commandline.zip -d allure-cli || (echo "Failed to unzip Allure CLI" && exit 1)
          ls -lh allure-cli/allure-2.20.1/bin # List extracted contents for debugging
          chmod +x allure-cli/allure-2.20.1/bin/allure # Ensure the binary is executable
          echo "${PWD}/allure-cli/allure-2.20.1/bin" >> $GITHUB_PATH # Add Allure CLI to PATH

      # Step 6: Run tests
      - name: Run tests
        env: # Set PYTHONPATH to ensure imports from src work
          PYTHONPATH: python_api/src
        run: |
          pytest python_api/tests --alluredir=allure-results

      # Step 7: Generate Allure Report
      - name: Generate Allure Report
        if: always() # Ensure this runs even if tests fail
        run: |
          allure generate allure-results --clean -o allure-report
      
      # Step 8: Upload Allure Report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
