name: Python Tests

on: 
  push: 
    branches: ["feature/allure-reports"]
  pull_request:
    branches: ["*"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repo
      - name: Check out repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python_api/requirements.txt
      
      # Step 4: Run tests
      - name: Run tests
        env: # Set PYTHONPATH to ensure imports from src work
          PYTHONPATH: python_api/src
        run: |
          pytest python_api/tests
      
      # Step 5: Generate Allure Report
      - name: Generate Allure Report
        if: always() # Ensure this runs even if tests fail
        run: |
          allure generate allure-results --clean -o allure-report
          env:
            ALLURE_DOWNLOAD: https://github.com/allure-framework/allure2/releases/latest/download/allure-commandline.zip
      
      # Step 6: Upload Allure Report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
